name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Change package name
      run: sed -i 's/@geoman-io\/leaflet-geoman-free/@skyraptor\/leaflet-geoman-free/' package.json

    - run: npm install

    - run: npm run build

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: 'public'
